### ISSUE TITLE
Enhance Module Discovery Protocol

### ISSUE THREAD

**Issue by PropGit** [dbetz/esp-link-parallax#1]
**[For discussion and implementation]**

Please enhance the module discovery protocol to increase chances of success across multiple network conditions.

The proposed [Parallax Wi-Fi Module Discovery Protocol](https://docs.google.com/document/d/18OmazwNGfv-ncFlEGvgWFr1DCC9apJlMHXvXU4tgjis/edit?usp=sharing) defines the desired behavior.  Ideas, comments, and updates should be made in that document, but discussion is welcome in this issue thread as well.

**Comment by dbetz** [comment]
I've implemented something similar to this proposal except using UDP in both directions. I'm going to close this issue for now. You can open it again if it turns out that the UDP responses are not adequate.
